export const BYTES_PER_MEGABYTE = 1024 * 1024;

export const DEFAULT_TASK_MEDIA_MAX_MB = 30;

export const DEFAULT_TASK_ATTACHMENT_MAX_BYTES = DEFAULT_TASK_MEDIA_MAX_MB * BYTES_PER_MEGABYTE;

export const DEFAULT_TASK_ATTACHMENT_FILENAME = "attachment";

export const HEX_RADIX = 16;

export const RANDOM_TOKEN_PREFIX_LENGTH = 2;

export const SIZE_DISPLAY_FRACTION_DIGITS = 0;
